<?php

namespace AppBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForList()
        {
            return $this->getEntityManager()
                ->createQuery(
                    'select id,published,published_at,title,LEFT(content,100) as content from AppBundle: blog'
                )
                ->getResult();
        }
        //je peux le faire à partir d'une nouvelle requete mais c'est tellement plus facile de le faire dans la vue

}
