<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function count()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT COUNT(p) AS somme FROM AppBundle: commentaire p '
            )
            ->getResult();
    }

}
